name: watch-upstream-base
on:
  schedule:                     # run every 30 min
    - cron:  '*/30 * * * *'
  workflow_dispatch:            # you can also fire it manually

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo jq
      - id: remote
        run: |
          DIGEST=$(skopeo inspect --format '{{.Digest}}' \
                  docker://quay.io/dfedora/fedora-coreos:stable)
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
      - id: local
        run: |
          echo "prev=$(git ls-remote origin refs/heads/base-digest |
                      cut -f1 | cut -c1-12 2>/dev/null || echo none)" \
               >> "$GITHUB_OUTPUT"
      - id: diff
        run: |
          if [ "${{ steps.remote.outputs.digest }}" != \
               "${{ steps.local.outputs.prev }}" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  trigger-build:
    needs: check
    if: needs.check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Kick off the build workflow
        run: gh workflow run build.yml -F base_digest=${{ needs.check.outputs.digest }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
